### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by jay-meister** [coletiv/puppeteer-pdf#10]
Hi again.

Sorry for 3rd issue but can you please close this issue when [this](https://github.com/coletiv/puppeteer-pdf/pull/9) version is available on Hex?

**Comment by jay-meister** [comment]
Hold up on that I need to make a change!

**Comment by speeddragon** [comment]
Let me know when I can publish to the hex.

**Comment by jay-meister** [comment]
https://github.com/coletiv/puppeteer-pdf/pull/11

When this is merged it's good to release 👍

**Comment by speeddragon** [comment]
Done, https://hexdocs.pm/puppeteer_pdf/1.0.1/readme.html
