### ISSUE TITLE
Briefly dependency not shown as required in the README

### ISSUE THREAD

**Issue by SylvainBigonneau** [coletiv/puppeteer-pdf#12]
As far as I have checked, I could not start generating a PDF with this module without installing and starting the `:briefly` dependency, as `Briefly.entry` is used by `Generate.from_string`.

Should we add it to the README?

**Comment by speeddragon** [comment]
I think you shouldn't need to add `:briefly` to your applications, because since Elixir 1.4 that is done automatically. What elixir version do you use ?

**Comment by SylvainBigonneau** [comment]
> I think you shouldn't need to add `:briefly` to your applications, because since Elixir 1.4 that is done automatically. What elixir version do you use ?

```
# elixir -v
Erlang/OTP 21 [erts-10.2.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.8.1 (compiled with Erlang/OTP 21)
```

**Comment by speeddragon** [comment]
Do you have `applications:` or `extra_applications:` in your `mix.exs` ? If you have the first one, you need to add `:briefly` to it, if you have extra_applications, can you provide the error message that appear when you try to generate a PDF ?

**Comment by SylvainBigonneau** [comment]
> Do you have `applications:` or `extra_applications:` in your `mix.exs` ? If you have the first one, you need to add `:briefly` to it, if you have extra_applications, can you provide the error message that appear when you try to generate a PDF ?

Ach, yes indeed, I am using `applications:` ! So I guess it's overwriting the default ones?

**Comment by speeddragon** [comment]
If you use `applications:` you will need to add every module that you use to it. You can read more in [here](https://www.amberbit.com/blog/2017/9/22/elixir-applications-vs-extra_applications-guide/). Either way, I can mention that on the README something in line like [this](https://github.com/thoughtbot/ex_machina#installation). If you want you can open a PR, or I will add it next week.

**Comment by SylvainBigonneau** [comment]
Thank you for your explanations, that cleared it up for me. I had already added `:briefly` to my `applications` list before opening this issue, and it had fixed my error, but I was in the idea that it was required (and as you seem to be saying it is likely not if using `extra_applications` instead) so I thought the README was missing that information, hence this issue.

I don't really know how one would make this clearer on the README without overexplaining basic configuration logic, so I won't try a PR for myself. But I would be grateful if you found the words!

Feel free to close this issue from now on :)
