### ISSUE TITLE
Windows OS :eaccess unable to execute puppeteer

### ISSUE THREAD

**Issue by tjchaplin** [coletiv/puppeteer-pdf#16]
When executing the tests on a windows OS, and the puppeteer-pdf, the application continues to get an :eaccess issue.

After downloading the code and further investigating I found that the handling of the puppeteer command in windows creates an error.  Here is some further reference:  

https://stackoverflow.com/questions/49164534/elixir-system-cmd-isnt-working

I have created a merge request that allows for a configuration item to be used for users using a windows machine.  I will create a pull request.  Not sure if there is a better solution, but this allowed me to continue, so I thought I would post it.  Open to other solutions as well.

Thanks for the library

**Comment by speeddragon** [comment]
Windows is a pain for developers, and in Elixir is even worse. As a personal suggestion I would recommend you to move do a *UNIX os, but of course I also want this library to be able to work on every OS that Elixir runs.

I've already left there some comments, feel free to comment there.

**Comment by dkaushik411** [comment]
@speeddragon We are facing same issue on windows with Elixir. Do we have a fix for this issue? Is the fix given by @tjchaplin not working or good? Actually we got stuck because of this issue on windows.

**Comment by speeddragon** [comment]
@dkaushik411, that fix should be working, but I still requested some minor changes to the PR before merging it into master. In the meantime you can use @tjchaplin fork.

**Comment by dkaushik411** [comment]
Thanks for the update @speeddragon
