### ISSUE TITLE
Should raise error if puppeteer-pdf executable is not found

### ISSUE THREAD

**Issue by sitch** [coletiv/puppeteer-pdf#19]
Should raise error if puppeteer-pdf executable is not found.  Had a production issue that would've been easier to debug had the lib called and raised on `.get_exec_version/0`

**Comment by speeddragon** [comment]
Yes, that is a good idea. I already have the code to that change, I will add it tomorrow.

**Comment by sitch** [comment]
Thanks @speeddragon
