### ISSUE TITLE
How to use in a Elixir Mix Project Locally with out -g option ?

### ISSUE THREAD

**Issue by blackode** [coletiv/puppeteer-pdf#29]
I am trying to use `puppeteer-pdf` locally in a `mix` project. 

I installed locally by running `npm install puppeteer-pdf`. 

This created a folder `node_modules` and inside it has two folders named `puppeteer` and `puppeteer-pdf` with some dependencies. 

In my `config.ex`, I configured the executable path to  `node_modules/puppeteer-pdf` 

```elixir
config :puppeteer_pdf, exec_path: Path.join(File.cwd!(), "node_modules/puppeteer-pdf")
```

After compiling, I tried to check version and generate a file from string like in the following way

```elixir
iex> PuppeteerPdf.get_exec_version()
""
iex> PuppeteerPdf.Generate.from_string "hello pdf", "pdfs/hello.pdf"
{:ok, ""}
```
I am not getting any errors nor pdf's generated. 

Am I missing Something here?

**Comment by blackode** [comment]
BTW, I resolved by updating config with following LOC in `config.ex`

```elixir
config :puppeteer_pdf, 
  exec_path: Path.join(File.cwd!(), "node_modules/.bin/puppeteer-pdf")
```

**Comment by tmpduarte** [comment]
Hi @blackode sorry for taking some time to answer. 

Glad you found a solution! We will probably include this solution in the readme, thank you for the contribution

**Comment by blackode** [comment]
Hi @tmpduarte 
Firstly, Thanks for amazing library :)
Glad to hear that..
