### ISSUE TITLE
Not generating tagged PDF even if accessible html is provided for conversion

### ISSUE THREAD

**Issue by dkaushik411** [coletiv/puppeteer-pdf#31]
We are passing an accessible html string(means screen reader reads header and paragraphs) for PDF conversion, but when it gets converted into PDF it is not a tagged PDF.  Screen reader just read the content but do not specify whether it is reading a header or paragraph. This library should generate tagged PDF.

**Comment by speeddragon** [comment]
Hi @dkaushik411 . Currently, this isn't supported because of Chromium [doesn't support it](https://bugs.chromium.org/p/skia/issues/detail?id=8148). This wrapper uses `puppeteer-pdf`, that uses [`puppeteer`](https://github.com/puppeteer/puppeteer/issues/3298), that uses `Chromium.`

**Comment by dkaushik411** [comment]
> Hi @dkaushik411 . Currently, this isn't supported because of Chromium [doesn't support it](https://bugs.chromium.org/p/skia/issues/detail?id=8148). This wrapper uses `puppeteer-pdf`, that uses [`puppeteer`](https://github.com/puppeteer/puppeteer/issues/3298), that uses `Chromium.`

**Comment by dkaushik411** [comment]
I guess this has been taken care of via this https://chromium-review.googlesource.com/c/chromium/src/+/1970742
